services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USERNAME: kubedevnews
      DB_PASSWORD: Pg#123
      DB_DATABASE: kubedevnews
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    user: node

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: kubedevnews
      POSTGRES_PASSWORD: Pg#123
      POSTGRES_DB: kubedevnews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubedevnews -d kubedevnews"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {} 
