version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
    command: npm start
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: kube_news_user
      POSTGRES_PASSWORD: kube_news_password
      POSTGRES_DB: kube_news_db
    ports:
      - "5432:5432"
