version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace:cached
      - app_node_modules:/workspace/node_modules
    environment:
      - DB_HOST=db
      - DB_USERNAME=kubedevnews
      - DB_PASSWORD=Pg#123
      - DB_DATABASE=kubedevnews
      - DB_PORT=5432
    depends_on:
      - db
    # Modifique o comando para configurar permissões
    command: >
      sh -c "
        mkdir -p /workspace/node_modules /workspace/views && 
        chown -R node:node /workspace/node_modules && 
        ln -sf /workspace/src/views/* /workspace/views/ && 
        sleep 10 && 
        node src/server.js
      "
    # Opcional: definir usuário explicitamente
    # user: "node"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kubedevnews
      POSTGRES_PASSWORD: Pg#123
      POSTGRES_DB: kubedevnews
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kubedevnews"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  app_node_modules:
