# .devcontainer/Dockerfile.dev
FROM node:16

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    procps \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

RUN npm install -g nodemon

RUN mkdir -p /workspace/node_modules \
    && chown -R node:node /workspace \
    && chown -R node:node /usr/local/lib/node_modules

USER node
CMD ["sleep", "infinity"]
