
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: volume
        source: app_node_modules
        target: /workspace/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USERNAME=kubedevnews
      - DB_PASSWORD=Pg#123
      - DB_DATABASE=kubedevnews
      - DB_PORT=5432
    command: nodemon src/server.js
    user: node

  db:
    ports:
      - "5433:5432"

volumes:
  app_node_modules:
  # postgres_data é herdado e não precisa ser redeclarado aqui
